image: node:latest

cache:
  key: node_modules
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    # - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
    - firebase deploy --non-interactive --token "$FIREBASE_TOKEN"
